### PR TITLE
Add a post about the Stanford medical webapp meeting

### PR DESCRIPTION
**Pull request by pieper**
Hi Andrey - 

Have a look at this.  I think I did the mechanics right but didn't preview it.  Also if you have any comments on the content of the post let me know.

-Steve

### CODE REVIEW

**Comment by fedorov** [comment]
Steve, thank you - this looks great to me!

Do you have a picture of the group, or do you think it is ok to take the one on the Kitware blog and add it here as well? I can integrate this PR and then do the picture and other edits if needed.

**Comment by pieper** [comment]
Great!

I didn't add the image since it was already in the linked documents, but
fine by me to add it if you want.  Since this was my first attempt I wasn't
sure how to lay out the image in the page - I didn't want to use it as a
background for the headline, like you did in the first post, and I didn't
look too carefully at how to put the image in line.  Would be happy to see
how you do it!

**Comment by pieper** [comment]
Cool - it's published!
http://qiicr.org/web/outreach/Medical-Imaging-Web-Apps/

But @fedorov a couple things to figure out:
- I didn't seem to get the bullet syntax correct - can you see what's wrong?  Maybe the space at the beginning of the line?
- It says it was written by you - I had updated the authors.yml but I thought it would pick up authorship by git committer but I guess not.

**Comment by fedorov** [comment]
Hmmmm ... I am sure I can figure the bullets (yes, I think it is spaces), but the authorship, this does not look good. I will look into this. Glad we are going through this exercise!

**Comment by fedorov** [comment]
All issues are now resolved.

For the reference, here are the different examples that demonstrate capabilities of the templates, I will add the link to the wiki page: https://phlow.github.io/feeling-responsive/blog/archive/

Thank you for your contribution!

**Comment by pieper** [comment]
Very nice!

**Pull request merged**
