### PR TITLE
adding RSNA2016 blog post

### PR DESCRIPTION
**Pull request by fedorov**

### CODE REVIEW

**Comment by pieper** [comment]
Looks good Andrey!

You could also include a mention of other Slicer-related activities at RSNA with this link.
https://www.na-mic.org/Wiki/index.php/RSNA_2016

**Comment by fedorov** [comment]
Makes sense! Can you add it? I would include with a paragraph summarizing updates in Slicer. Do we have one? I cannot work on it right now, but if you don't have time I will add in the afternoon or so.

**Comment by pieper** [comment]
I hope you don't mind I didn't bother with a pull request!

https://github.com/QIICR/qiicr.github.io/commit/9320eec600c2aec251b8847df1d51f5c83f0369b

**Comment by fedorov** [comment]
It's ok - in this particular case, these PRs are symbolic anyway, because I haven't figured out a way to generate a fully functional instance locally, so github web hosting serves as a test.

I did few minor edits, but looks good otherwise. Thank you!

**Pull request merged**
